import { rooms, facilities, CONTACT } from '../data';
import { Check, Users, BedDouble, Wifi, CalendarDays } from 'lucide-react';
export default function Accommodation(){
 const submit=(e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=`Hi Sandy-Blu Guest House, I would like to check availability.\nCheck-in: ${f.get('checkin')}\nCheck-out: ${f.get('checkout')}\nGuests: ${f.get('guests')}\nRoom: ${f.get('room')}`;window.open(`https://wa.me/${CONTACT.phone}?text=${encodeURIComponent(msg)}`,'_blank')};
 return <div className="pt-20 bg-[#fbfaf7] min-h-screen"><section className="relative h-80 overflow-hidden"><img src="/images/room.jpg" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-white/55"/><div className="absolute inset-0 flex flex-col items-center justify-center"><h1 className="font-serif text-5xl text-[#062f4d]">ACCOMMODATION</h1><p className="text-slate-700 mt-2">Comfort. Style. Serenity.</p></div></section>
 <div className="max-w-7xl mx-auto px-4 py-14"><p className="text-center max-w-3xl mx-auto text-slate-600">Our beautifully appointed rooms are designed with your comfort in mind. Whether you're here for business or leisure, we have the perfect space for you.</p><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mt-10">{rooms.map(r=><article key={r.name} className="bg-white rounded-xl overflow-hidden border shadow-sm"><img src={r.image} className="h-52 w-full object-cover"/><div className="p-5 text-center"><h2 className="font-bold text-[#062f4d]">{r.name.toUpperCase()}</h2><p className="text-sm text-slate-500 mt-3 min-h-12">{r.description}</p><div className="flex justify-center gap-4 text-slate-400 my-4"><Users size={17}/><BedDouble size={17}/><Wifi size={17}/></div><a href="#availability" className="inline-block bg-[#b88b3f] text-white px-5 py-2 rounded text-xs font-bold">VIEW DETAILS</a></div></article>)}</div>
 <section className="mt-14 grid lg:grid-cols-2 bg-[#062f4d] text-white rounded-2xl overflow-hidden"><img src="/images/facilities-pool.jpg" className="w-full h-full min-h-80 object-cover"/><div className="p-8"><h2 className="font-serif text-3xl">FACILITIES</h2><div className="grid sm:grid-cols-2 gap-3 mt-5">{facilities.map(x=><div className="flex gap-2 text-sm" key={x}><Check className="text-[#d7a852] shrink-0" size={18}/>{x}</div>)}</div></div></section>
 <section id="availability" className="mt-14 bg-white border rounded-2xl p-6 shadow-sm scroll-mt-28"><h2 className="font-bold text-[#062f4d] flex items-center gap-2"><CalendarDays/> CHECK AVAILABILITY & BOOK ONLINE</h2><form onSubmit={submit} className="grid md:grid-cols-4 gap-4 mt-5"><label className="text-xs font-bold">Check-in<input required type="date" name="checkin" className="mt-2 w-full border rounded px-3 py-3 font-normal"/></label><label className="text-xs font-bold">Check-out<input required type="date" name="checkout" className="mt-2 w-full border rounded px-3 py-3 font-normal"/></label><label className="text-xs font-bold">Guests<select name="guests" className="mt-2 w-full border rounded px-3 py-3 font-normal"><option>1 Guest</option><option>2 Guests</option><option>3 Guests</option><option>4+ Guests</option></select></label><label className="text-xs font-bold">Room<select name="room" className="mt-2 w-full border rounded px-3 py-3 font-normal">{rooms.map(r=><option key={r.name}>{r.name}</option>)}</select></label><button className="md:col-span-4 justify-self-start bg-[#b88b3f] text-white px-7 py-3 rounded font-bold">CHECK AVAILABILITY</button></form></section>
 </div></div>}
