import { Link } from 'react-router-dom';
import { BedDouble, Waves, Wifi, ShieldCheck, Coffee, Umbrella, Plane, ShoppingBag, MapPin } from 'lucide-react';

const amen=[['LUXURY\nROOMS',BedDouble],['SWIMMING\nPOOL',Waves],['FREE\nWIFI',Wifi],['SECURE\nPARKING',ShieldCheck],['BREAKFAST\nAVAILABLE',Coffee],['CLOSE TO\nTHE BEACH',Umbrella]];
export default function Home(){return <div className="pt-20">
 <section className="relative min-h-[610px] overflow-hidden flex items-center"><img src="/images/hero-coast.jpg" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/75 to-transparent"/><div className="relative max-w-7xl mx-auto px-5 w-full py-16"><div className="max-w-2xl"><p className="font-script text-4xl text-[#b88b3f] italic">Welcome to</p><h1 className="font-serif text-6xl md:text-8xl leading-[.9] text-[#062f4d]">Sandy-Blu<br/>Guest House</h1><p className="mt-5 font-bold text-[#062f4d] tracking-wide">YOUR COASTAL ESCAPE IN UMHLANGA ROCKS</p><p className="mt-4 text-lg text-slate-700 max-w-xl">Experience comfort, elegance and warm South African hospitality just minutes from the beach.</p><Link to="/accommodation#availability" className="inline-flex mt-6 bg-[#062f4d] text-white px-7 py-4 rounded-md font-bold">BOOK YOUR STAY</Link></div></div></section>
 <section className="bg-white border-y"><div className="max-w-6xl mx-auto px-4 py-9 grid grid-cols-3 md:grid-cols-6 gap-6">{amen.map(([txt,Icon]:any)=><div className="text-center text-[#062f4d]" key={txt as string}><Icon className="mx-auto text-[#b88b3f]" size={34}/><p className="text-xs font-bold whitespace-pre-line mt-2">{txt as string}</p></div>)}</div></section>
 <section className="max-w-7xl mx-auto px-4 py-16 grid lg:grid-cols-[.85fr_1.5fr] gap-10 items-center"><div><p className="text-[#b88b3f] font-bold text-sm">ABOUT SANDY-BLU</p><h2 className="font-serif text-4xl text-[#062f4d] mt-2">Relax. Unwind.<br/>Feel at Home.</h2><p className="text-slate-600 mt-5 leading-7">Sandy-Blu Guest House offers stylish, well appointed rooms with premium amenities, a sparkling pool and a peaceful atmosphere to ensure you have a memorable stay.</p><Link to="/explore-contact" className="inline-block mt-6 bg-[#062f4d] text-white px-6 py-3 rounded-md font-bold text-sm">LEARN MORE ABOUT US</Link></div><div className="grid grid-cols-3 gap-4"><img src="/images/pool.jpg" className="rounded-lg h-64 w-full object-cover"/><img src="/images/breakfast.jpg" className="rounded-lg h-64 w-full object-cover"/><img src="/images/room.jpg" className="rounded-lg h-64 w-full object-cover"/></div></section>
 <section className="bg-[#062f4d] text-white"><div className="max-w-7xl mx-auto px-4 py-9 grid md:grid-cols-3 gap-8"><div className="flex gap-4 items-center"><Plane className="text-[#d7a852]" size={38}/><p className="font-bold">15 MINUTES FROM<br/>KING SHAKA INTERNATIONAL AIRPORT</p></div><div className="flex gap-4 items-center md:border-x md:px-8 border-white/20"><ShoppingBag className="text-[#d7a852]" size={38}/><p className="font-bold">MINUTES FROM<br/>GATEWAY THEATRE OF SHOPPING</p></div><div className="flex gap-4 items-center"><MapPin className="text-[#d7a852]" size={38}/><p className="font-bold">WALK TO UMHLANGA<br/>BEACH & VILLAGE</p></div><p className="md:col-span-3 text-center font-serif italic text-xl text-[#d7a852] mt-2">“Luxury by the Ocean. Hospitality from the Heart.”</p></div></section>
</div>}
